import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./os-theme-final.css";
import "./metaos-readability.css";
import { CopyVisibleMetaFilter } from "@/components/meta/CopyVisibleMetaFilter";
import { MetaOSClassicUXLayer } from "@/components/meta-v2/shell/MetaOSClassicUXLayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><CopyVisibleMetaFilter />
        <MetaOSClassicUXLayer />
        {children}</body>
    </html>
  );
}
